### PR TITLE
Https endpoint

### PR DESCRIPTION
**Pull request by keltia**
Basic patch.  "rcov" issue and "rdoc" issues (probably because pastebin has not followed the recent changes in both?) not solved but it enable installation.  Haven't bumped VERSION, I'll leave that to you :)

### CODE REVIEW

**Comment by dougsko** [comment]
I got your changes in there, updated the tests, and made some other small changes to get the package up to date.  Thanks for reaching out and contributing to this project!

**Comment by keltia** [comment]
Hello,

According to Doug Prostko:
> I got your changes in there, updated the tests, and made some other small changes to get the package up to date.  Thanks for reaching out and contributing to this project!

It would have been better to accept my PR and add your own changes than doing it that way, w/o attribution…

Thanks anyway.

**Comment by dougsko** [comment]
Hi Ollivier,

Sorry I wasn't thinking about the attribution log in regards to landing the PR.  I do really appreciate contributions though, so I added a THANKS file to give you credit for helping out.

**Comment by keltia** [comment]
According to Doug Prostko:
> Sorry I wasn't thinking about the attribution log in regards to landing the PR.  I do really appreciate contributions though, so I added a THANKS file to give you credit for helping out.

No worries, thanks!

-- 
Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- roberto@keltia.net
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Pull request closed without merging**
